#!/usr/bin/env python3
"""
Generate 80 sensor positions on a sphere using the Fibonacci sphere algorithm.
Bottom 30 degrees (z < cos(150deg) = -0.866) have no sensors.

Output: C header file with 80 sensor unit vectors, sorted top-to-bottom.
"""

import math
import sys
import os

GOLDEN_RATIO = (1 + math.sqrt(5)) / 2

def fibonacci_sphere(n_points):
    points = []
    for i in range(n_points):
        theta = math.acos(1 - 2 * (i + 0.5) / n_points)
        phi = 2 * math.pi * i / GOLDEN_RATIO
        x = math.sin(theta) * math.cos(phi)
        y = math.sin(theta) * math.sin(phi)
        z = math.cos(theta)
        points.append((x, y, z))
    return points

def main():
    Z_MIN = math.cos(math.radians(150))  # -0.866: bottom 30 degree boundary
    target = 80

    # Brute-force find optimal N such that filtered count = target
    n_full = target
    while True:
        all_pts = fibonacci_sphere(n_full)
        filtered = [p for p in all_pts if p[2] >= Z_MIN]
        if len(filtered) == target:
            break
        n_full += 1
        if n_full > target * 2:
            print("Warning: Could not find exact match, using closest", file=sys.stderr)
            break

    # Sort by z descending (top to bottom)
    filtered.sort(key=lambda p: -p[2])

    out_path = os.path.join(os.path.dirname(__file__), '..', 'include', 'sensor_positions.h')
    with open(out_path, 'w') as f:
        f.write("""#ifndef SENSOR_POSITIONS_H
#define SENSOR_POSITIONS_H

#include <stdint.h>

typedef struct {{
    float x;
    float y;
    float z;
}} vec3_t;

/*
 * 80 sensor positions on the unit sphere.
 * Sorted from top (z ~ 1.0) to bottom (z ~ -0.866).
 * Bottom 30 degrees (z < -0.866) have no sensors.
 * Generated by fibonacci_sphere({n_full}) algorithm.
 */
#define SENSOR_COUNT {count}

const vec3_t SENSOR_POSITIONS[SENSOR_COUNT] = {{
""".format(n_full=n_full, count=len(filtered)))

        for i, (x, y, z) in enumerate(filtered):
            f.write("    {{ {:.7f}f, {:.7f}f, {:.7f}f }},  // #{i:02d}, z={z:.4f}\n".format(x, y, z, i=i, z=z))

        f.write("""}};

/*
 * Each sensor's physical channel ID -> position index mapping.
 * During auto-calibration, this array is filled.
 * Default: identity mapping (physical channel i = position i).
 */
extern uint8_t g_channel_to_position[SENSOR_COUNT];

#endif // SENSOR_POSITIONS_H
""")

    print(f"Generated {len(filtered)} sensor positions -> {out_path}")
    print(f"  z range: {min(z for _,_,z in filtered):.4f} to {max(z for _,_,z in filtered):.4f}")

    # Print summary table for documentation
    print("\nZ-level distribution:")
    buckets = {}
    for _, _, z in filtered:
        bucket = int(z * 10) * 10
        buckets[bucket] = buckets.get(bucket, 0) + 1
    for z_bucket in sorted(buckets.keys(), reverse=True):
        print(f"  z in [{z_bucket/10:.1f}, {(z_bucket+10)/10:.1f}): {buckets[z_bucket]} sensors")

if __name__ == '__main__':
    main()
