#ifndef SENSOR_POSITIONS_H
#define SENSOR_POSITIONS_H

#include <stdint.h>
#include "config.h"

typedef struct {
    float x;
    float y;
    float z;
} vec3_t;

/*
 * 80 sensor positions on the unit sphere.
 * Sorted from top (z ~ 1.0) to bottom (z ~ -0.866).
 * Bottom 30 degrees (z < -0.866) have no sensors.
 * Generated by fibonacci_sphere(86) algorithm.
 */

extern const vec3_t SENSOR_POSITIONS[SENSOR_COUNT];

/*
 * Each sensor's physical channel ID -> position index mapping.
 * During auto-calibration, this array is filled.
 * Default: identity mapping (physical channel i = position i).
 */
extern uint8_t g_channel_to_position[SENSOR_COUNT];

#endif // SENSOR_POSITIONS_H
