[platformio]
src_dir = main

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Build flags
build_flags =
    -DCONFIG_LOG_DEFAULT_LEVEL=3
    -DCONFIG_I2C_SUPPRESS_DEPRECATE_WARN=y
    -Os

; Libraries (managed via platformio lib deps)
lib_deps =

; Serial port (adjust to your system)
upload_port = COM3
monitor_port = COM3
